### ISSUE TITLE
Pop-up focus

### ISSUE THREAD

**Issue by jEsuSdA** [lbalazscs/Pixelitor#96]
Hi again!

I noticed that when any new popup window is opened, it is not placed on the screen when Pixelitor is running.

I have two monitors and I run pixelitor in the big one (on the right) but all the popup windows are opened in the center of the left monitor.

Is there any way to force pixelitor to open new popup windows in any of these possible solutions?:
- on the screen where pixelitor is running
- on top of the pixelitor main window
- in the last position where last popup window was closed

Thanks a lot!

**Comment by lbalazscs** [comment]
I will investigate this.  Actually even with a single monitor it would be nice if dialog windows opened where the last one was closed.

**Comment by lbalazscs** [comment]
I committed a change to GitHub that should fix the problem. It should work line this:

1. Popup windows open on the same monitor as the main window
2. Popup windows are screen-centered except for the filter windows which are right-aligned to the main window
3. All popup windows remember their last position and they go there if used again, overriding the first two rules. These positions are not remembered after a restart.

**Comment by jEsuSdA** [comment]
Great!!!
I'm going to try it now!!!

**Comment by jEsuSdA** [comment]
It works very well! And IMHO makes Pixelitor more easy to use.
Thanks a lot, @lbalazscs .

I have a suggestiong about the splash screen while Pixelitor loading:
- Now the splash screen appears in the middle of my entire desktop (As I have two monitors, it actually appears at the left of the main screen)

Could be possible make the splash screen screen-centered too?

**Comment by PozhidaevYury** [comment]
Problem persist on the macOS Catalina 10.15.7.

1. File -> Automate -> Batch Resize.
2. Click on the Browse button.

No focus on the select folder window.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/43886351/97100003-cedcad00-16c1-11eb-878c-9eb9f8ce1a57.png">

**Comment by lbalazscs** [comment]
The original problem is fixed in Pixelitor 4.3.0, and I could not reproduce the second problem.
